import SwiftUI

struct AIConsentView: View {
    @AppStorage("hasGrantedAIConsent") private var hasGrantedAIConsent = false

    var body: some View {
        ZStack {
            Color(hex: "18120C").ignoresSafeArea()

            VStack(spacing: 0) {
                Spacer()

                // Icon
                Image(systemName: "cpu.fill")
                    .font(.system(size: 40))
                    .foregroundColor(Color(hex: "C8A96E"))
                    .padding(.bottom, 28)

                Text("How AURA uses AI")
                    .font(.system(size: 26, weight: .semibold, design: .default))
                    .foregroundColor(Color(hex: "F5F0E8"))
                    .multilineTextAlignment(.center)
                    .padding(.bottom, 16)

                Text("To generate your portraits and videos, AURA sends your photos to Google AI (Gemini and Veo). No data is used to train AI models.")
                    .font(.system(size: 15))
                    .foregroundColor(Color(hex: "A09080"))
                    .multilineTextAlignment(.center)
                    .lineSpacing(4)
                    .padding(.horizontal, 32)
                    .padding(.bottom, 32)

                // Detail rows
                VStack(spacing: 12) {
                    ConsentRow(
                        icon: "photo.fill",
                        title: "Your photos",
                        detail: "Sent to Google AI to generate your portrait"
                    )
                    ConsentRow(
                        icon: "video.fill",
                        title: "Your videos",
                        detail: "Generated by Google Veo from your image"
                    )
                    ConsentRow(
                        icon: "lock.fill",
                        title: "Your privacy",
                        detail: "Photos are not stored or used for training"
                    )
                }
                .padding(.horizontal, 24)
                .padding(.bottom, 40)

                // CTA
                Button {
                    hasGrantedAIConsent = true
                } label: {
                    Text("I understand — Continue")
                        .font(.system(size: 16, weight: .semibold))
                        .foregroundColor(Color(hex: "18120C"))
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 16)
                        .background(Color(hex: "C8A96E"))
                        .cornerRadius(14)
                }
                .padding(.horizontal, 24)
                .padding(.bottom, 16)

                Link("Privacy Policy", destination: URL(string: "https://matthieugb.github.io/aura-app/privacy")!)
                    .font(.system(size: 13))
                    .foregroundColor(Color(hex: "C8A96E").opacity(0.7))
                    .padding(.bottom, 40)
            }
        }
    }
}

private struct ConsentRow: View {
    let icon: String
    let title: String
    let detail: String

    var body: some View {
        HStack(spacing: 14) {
            Image(systemName: icon)
                .font(.system(size: 16))
                .foregroundColor(Color(hex: "C8A96E"))
                .frame(width: 32)

            VStack(alignment: .leading, spacing: 2) {
                Text(title)
                    .font(.system(size: 14, weight: .semibold))
                    .foregroundColor(Color(hex: "F5F0E8"))
                Text(detail)
                    .font(.system(size: 13))
                    .foregroundColor(Color(hex: "A09080"))
            }
            Spacer()
        }
        .padding(14)
        .background(Color(hex: "201810"))
        .cornerRadius(10)
    }
}
